server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5441/webflux-postgres-db
    username: root
    password: root

  datasource:
    url: jdbc:postgresql://localhost:5441/webflux-postgres-db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5441/webflux-postgres-db
    user: root
    password: root
    locations: classpath:db/migration
    enabled: true

jwt:
  password:
    encoder:
      secret: salmasdkmalksdmlkasmdlkasmdlkmqwpodmpokpokpo
      iteration: 64
      keylength: 256
  secret: lsmclakmclkmqmcaqwkopekpqowkdpoqwkdpokqw
  expiration: 3600
  issuer: shyngys